name       : wpebackend-fdo
version    : 1.14.0
release    : 9
source     :
    - https://wpewebkit.org/releases/wpebackend-fdo-1.14.0.tar.xz : e75b0cb2c7145448416e8696013d8883f675c66c11ed750e06865efec5809155
license    : BSD-2-Clause
component  : programming.library
summary    : FreeDesktop backend for WPE WebKit
description: |
    FreeDesktop backend for WPE WebKit
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(glib-2.0)
    - pkgconfig(wayland-egl-backend)
    - pkgconfig(wpe-1.0)
    - pkgconfig(x11)
rundeps    :
    - devel : libwpe-devel
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
