name       : wpebackend-fdo
version    : 1.10.0
release    : 8
source     :
    - https://wpewebkit.org/releases/wpebackend-fdo-1.10.0.tar.xz : b89dfd3500a4dec711132cd7bff72599e67d56a419d000730e14bb99547509cc
license    : BSD-2-Clause
component  : programming.library
summary    : FreeDesktop backend for WPE WebKit
description: |
    FreeDesktop backend for WPE WebKit
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(glib-2.0)
    - pkgconfig(wayland-egl-backend)
    - pkgconfig(wpe-1.0)
    - pkgconfig(x11)
rundeps    :
    - devel: libwpe-devel
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
