name       : wpebackend-fdo
version    : 1.8.0
release    : 4
source     :
    - https://wpewebkit.org/releases//wpebackend-fdo-1.8.0.tar.xz : 9652a99c75fe1c6eab0585b6395f4e104b2427e4d1f42969f1f77df29920d253
license    : BSD-2-Clause
component  : programming.library
summary    : FreeDesktop backend for WPE WebKit
description: |
    FreeDesktop backend for WPE WebKit
builddeps  :
    - pkgconfig(epoxy)
    - pkgconfig(glib-2.0)
    - pkgconfig(wayland-egl-backend)
    - pkgconfig(wpe-1.0)
    - pkgconfig(x11)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
